definitions:
  database.Delivery:
    properties:
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      order_uid:
        type: string
      phone:
        type: string
      region:
        type: string
      updatedAt:
        type: string
      zip:
        type: integer
    type: object
  database.Item:
    properties:
      brand:
        type: string
      chrt_id:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      item_id:
        type: integer
      name:
        type: string
      nm_id:
        type: integer
      order_uid:
        type: string
      price:
        type: integer
      rid:
        type: string
      sale:
        type: integer
      size:
        type: string
      status:
        type: integer
      total_price:
        type: integer
      track_number:
        type: string
      updatedAt:
        type: string
    type: object
  database.Order:
    properties:
      createdAt:
        type: string
      customer_id:
        type: integer
      date_created:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      delivery:
        $ref: '#/definitions/database.Delivery'
      delivery_service:
        type: string
      entry:
        type: string
      id:
        type: integer
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/database.Item'
        type: array
      locale:
        type: string
      oof_shard:
        type: string
      order_uid:
        type: string
      payment:
        $ref: '#/definitions/database.Payment'
      shard_key:
        type: string
      sm_id:
        type: integer
      track_number:
        type: string
      updatedAt:
        type: string
    type: object
  database.Payment:
    properties:
      amount:
        type: integer
      bank:
        type: string
      createdAt:
        type: string
      currency:
        type: string
      custom_fee:
        type: integer
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      delivery_cost:
        type: integer
      goods_total:
        type: integer
      id:
        type: integer
      order_uid:
        type: string
      payment_dt:
        type: string
      provider:
        type: string
      request_id:
        type: integer
      transaction:
        type: string
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
  description: API Server for demonstrate work
  title: WBTech Task0 Go API
  version: 0.0.1
paths:
  /get_order/{order_uid}:
    get:
      consumes:
      - application/json
      description: Retrieves details of an order by order UID
      parameters:
      - description: Order UID
        in: path
        name: order_uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Detailed order information
          schema:
            $ref: '#/definitions/database.Order'
        "400":
          description: Bad request if no order found or other request error
        "500":
          description: Internal server error if the order cannot be loaded
      summary: Get a single order by UID
      tags:
      - orders
  /get_orders:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all orders from the database
      produces:
      - application/json
      responses:
        "200":
          description: A list of orders
          schema:
            items:
              $ref: '#/definitions/database.Order'
            type: array
        "400":
          description: Bad request if specific error on getting orders
        "500":
          description: Internal server error if orders cannot be loaded
      summary: Get list of all orders
      tags:
      - orders
swagger: "2.0"
